# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dca4bb9c13337ed34cba6ebd906a9678099d30ef56949851f4372efc57eb538c4e979b4699a23c5f810d2aa6730f02aa3d1ddac7e7fd6805edc07f3c8e7de3ab

test:
  secret_key_base: 300bddabc79b7803e64165e26a73816d38da63f54eee30b451f799db2cc2a4337e6dadd728318d2d80cc0eed5c014c19fd111e2323b6e21ed11cf832742cbcb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
